ANONYMOUS_USERNAME = "Anonymous"
ANONYMOUS_GROUPNAME = "Anonymous users"
KORPPI_GROUPNAME = "Korppi users"
LOGGED_IN_GROUPNAME = "Logged-in users"
LOGGED_IN_USERNAME = "Logged-in user"
ADMIN_GROUPNAME = "Administrators"
LARGE_GROUPS = {ANONYMOUS_GROUPNAME, KORPPI_GROUPNAME, LOGGED_IN_GROUPNAME}
SPECIAL_GROUPS = {ANONYMOUS_GROUPNAME, KORPPI_GROUPNAME, LOGGED_IN_GROUPNAME, ADMIN_GROUPNAME}
