"""add manager column for eventgroup

Revision ID: 0212bfd7beee
Revises: 338d9318ccbb
Create Date: 2022-05-13 16:10:27.479365

"""

# revision identifiers, used by Alembic.
revision = "0212bfd7beee"
down_revision = "338d9318ccbb"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("eventgroup", sa.Column("manager", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("eventgroup", "manager")
    # ### end Alembic commands ###
