"""Add max tokens per user to Policy table and rename previous max tokens to token pool.

Revision ID: 03399434d3b8
Revises: 30b749def124
Create Date: 2026-05-03 04:19:04.552749

"""

# revision identifiers, used by Alembic.
revision = "03399434d3b8"
down_revision = "30b749def124"

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_rule", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "indexed_document_ids", postgresql.ARRAY(sa.Integer()), nullable=False
            )
        )
        batch_op.drop_column("indexed_chunk_ids")

    with op.batch_alter_table("policy", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("max_tokens_per_user", sa.Integer(), nullable=False)
        )
        batch_op.add_column(sa.Column("token_pool", sa.Integer(), nullable=False))
        batch_op.drop_column("max_tokens")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("policy", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("max_tokens", sa.INTEGER(), autoincrement=False, nullable=False)
        )
        batch_op.drop_column("token_pool")
        batch_op.drop_column("max_tokens_per_user")

    with op.batch_alter_table("llm_rule", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "indexed_chunk_ids",
                postgresql.ARRAY(sa.INTEGER()),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.drop_column("indexed_document_ids")

    # ### end Alembic commands ###
