"""Badge table: add columns created_by, created, modified_by, modified, deleted_by, deleted

Revision ID: 04901bdb0c13
Revises: ac701c242157
Create Date: 2025-03-04 13:24:38.071840

"""

# revision identifiers, used by Alembic.
revision = '04901bdb0c13'
down_revision = 'ac701c242157'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('modified_by', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('modified', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('deleted_by', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=False))
        batch_op.create_foreign_key(None, 'usergroup', ['deleted_by'], ['id'])
        batch_op.create_foreign_key(None, 'usergroup', ['created_by'], ['id'])
        batch_op.create_foreign_key(None, 'usergroup', ['modified_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('deleted')
        batch_op.drop_column('deleted_by')
        batch_op.drop_column('modified')
        batch_op.drop_column('modified_by')
        batch_op.drop_column('created')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
