"""Add table for UserLoginCode

Revision ID: 0755b11fe161
Revises: 14a649d37bc3
Create Date: 2023-11-16 08:53:49.233928

"""

# revision identifiers, used by Alembic.
revision = '0755b11fe161'
down_revision = '14a649d37bc3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userlogincode',
    sa.Column('code', sa.String(length=9), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('association', sa.String(), nullable=False),
    sa.Column('activation_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activation_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activation_status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['usergroup.id'], ),
    sa.PrimaryKeyConstraint('code', 'id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userlogincode')
    # ### end Alembic commands ###
