"""Add last_seen to internalmessage_readreceipt

Revision ID: 0c0ed7527991
Revises: cfb47bb4ea55
Create Date: 2022-02-21 14:22:11.729286

"""

# revision identifiers, used by Alembic.
revision = "0c0ed7527991"
down_revision = "cfb47bb4ea55"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "internalmessage_readreceipt",
        sa.Column("last_seen", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("internalmessage_readreceipt", "last_seen")
    # ### end Alembic commands ###
