"""Add message column to BadgeGiven table

Revision ID: 14599eeb4eeb
Revises: a01677947fcf
Create Date: 2025-02-24 09:24:35.314195

"""

# revision identifiers, used by Alembic.
revision = '14599eeb4eeb'
down_revision = 'a01677947fcf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badgegiven', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badgegiven', schema=None) as batch_op:
        batch_op.drop_column('message')

    # ### end Alembic commands ###
