"""Delete teachers from LLMRule table and policy_type from Policy table.

Revision ID: 165d17108346
Revises: 24f3ff2b4ef5
Create Date: 2026-05-21 15:28:08.112682

"""

# revision identifiers, used by Alembic.
revision = "165d17108346"
down_revision = "24f3ff2b4ef5"

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_rule", schema=None) as batch_op:
        batch_op.drop_column("teachers")

    with op.batch_alter_table("policy", schema=None) as batch_op:
        batch_op.drop_column("policy_type")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("policy", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("policy_type", sa.VARCHAR(), autoincrement=False, nullable=False)
        )

    with op.batch_alter_table("llm_rule", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "teachers",
                postgresql.ARRAY(sa.INTEGER()),
                autoincrement=False,
                nullable=False,
            )
        )

    # ### end Alembic commands ###
