"""Add Event.send_notifications

Revision ID: 1a8792054f77
Revises: a52fd641921f
Create Date: 2022-08-19 09:28:43.420942

"""

# revision identifiers, used by Alembic.
revision = "1a8792054f77"
down_revision = "a52fd641921f"

import sqlalchemy as sa
from alembic import op


# noinspection SqlResolve
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("event", sa.Column("send_notifications", sa.Boolean(), nullable=True))
    op.execute("UPDATE event SET send_notifications = True")
    op.alter_column("event", "send_notifications", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("event", "send_notifications")
    # ### end Alembic commands ###
