"""Add default_comment column to velpcontent table.

Revision ID: 209fc28604ba
Revises: 70a159e42ba6
Create Date: 2016-12-21 08:58:18.215477

"""

# revision identifiers, used by Alembic.
revision = '209fc28604ba'
down_revision = '70a159e42ba6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('velpcontent', sa.Column('default_comment', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('velpcontent', 'default_comment')
    ### end Alembic commands ###
