"""Add BlockRelevance table to the database.

Revision ID: 2236e3460ce2
Revises: 55d075fdf05b
Create Date: 2018-11-29 09:57:50.561764

"""

# revision identifiers, used by Alembic.
revision = '2236e3460ce2'
down_revision = '55d075fdf05b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blockrelevance',
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('relevance', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['block.id'], ),
    sa.PrimaryKeyConstraint('block_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blockrelevance')
    # ### end Alembic commands ###
