"""Badge table: edit some relationships to nullable many-to-one

Revision ID: 26c1a3c1beeb
Revises: c4dedd2d29f5
Create Date: 2025-03-05 10:41:28.332178

"""

# revision identifiers, used by Alembic.
revision = '26c1a3c1beeb'
down_revision = 'c4dedd2d29f5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.alter_column('modified_by',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('deleted_by',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('restored_by',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.alter_column('restored_by',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('deleted_by',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('modified_by',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
