"""badgegiven table: set all variables to use Mapped-syntax and create columns given_by, given, withdrawn_by, withdrawn, undo_withdrawn_by and undo_withdrawn

Revision ID: 2a281f62cbfe
Revises: 31e9a4dd646b
Create Date: 2025-03-07 07:34:56.782946

"""

# revision identifiers, used by Alembic.
revision = '2a281f62cbfe'
down_revision = '31e9a4dd646b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badgegiven', schema=None) as batch_op:
        batch_op.add_column(sa.Column('given_by', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('given', sa.DateTime(timezone=True), nullable=False))
        batch_op.add_column(sa.Column('withdrawn_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('withdrawn', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('undo_withdrawn_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('undo_withdrawn', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=False)
        batch_op.create_foreign_key(None, 'usergroup', ['given_by'], ['id'])
        batch_op.create_foreign_key(None, 'usergroup', ['undo_withdrawn_by'], ['id'])
        batch_op.create_foreign_key(None, 'usergroup', ['withdrawn_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badgegiven', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('undo_withdrawn')
        batch_op.drop_column('undo_withdrawn_by')
        batch_op.drop_column('withdrawn')
        batch_op.drop_column('withdrawn_by')
        batch_op.drop_column('given')
        batch_op.drop_column('given_by')

    # ### end Alembic commands ###
