"""Add cascade delete to llm_rule foreign keys

Revision ID: 2de839f71c3e
Revises: 9c9b96ae1505
Create Date: 2026-04-24 17:54:46.522523

"""

# revision identifiers, used by Alembic.
revision = '2de839f71c3e'
down_revision = '9c9b96ae1505'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policy', schema=None) as batch_op:
        batch_op.drop_constraint('policy_llm_rule_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'llm_rule', ['llm_rule_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('usage', schema=None) as batch_op:
        batch_op.drop_constraint('usage_llm_rule_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'llm_rule', ['llm_rule_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('usage_llm_rule_id_fkey', 'llm_rule', ['llm_rule_id'], ['id'])

    with op.batch_alter_table('policy', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('policy_llm_rule_id_fkey', 'llm_rule', ['llm_rule_id'], ['id'])

    # ### end Alembic commands ###
