"""Add system_prompt_path for LLMRule table

Revision ID: 30b749def124
Revises: 7c186be71ec9
Create Date: 2026-04-27 15:25:07.741537

"""

# revision identifiers, used by Alembic.
revision = "30b749def124"
down_revision = "7c186be71ec9"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_rule", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("system_prompt_path", sa.String(), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_rule", schema=None) as batch_op:
        batch_op.drop_column("system_prompt_path")

    # ### end Alembic commands ###
