"""Add context_group to Badge table

Revision ID: 3188df30c0d1
Revises: 14599eeb4eeb
Create Date: 2025-03-03 09:37:01.916478

"""

# revision identifiers, used by Alembic.
revision = '3188df30c0d1'
down_revision = '14599eeb4eeb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('context_group', sa.String(), nullable=False))

    with op.batch_alter_table('badgegiven', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badgegiven', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.drop_column('context_group')

    # ### end Alembic commands ###
