"""badge table: set modified, deleted and restored to optional

Revision ID: 31e9a4dd646b
Revises: 7b35e7ee62f6
Create Date: 2025-03-06 12:51:06.374900

"""

# revision identifiers, used by Alembic.
revision = "31e9a4dd646b"
down_revision = "7b35e7ee62f6"

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("badge", schema=None) as batch_op:
        batch_op.alter_column(
            "modified", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True
        )
        batch_op.alter_column(
            "deleted", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True
        )
        batch_op.alter_column(
            "restored", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("badge", schema=None) as batch_op:
        batch_op.alter_column(
            "restored",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=False,
        )
        batch_op.alter_column(
            "deleted", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False
        )
        batch_op.alter_column(
            "modified",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=False,
        )

    # ### end Alembic commands ###
