"""Add badges and badgesgiven

Revision ID: 32447299a7db
Revises: a1485d740d43
Create Date: 2025-03-06 12:21:46.764175

"""

# revision identifiers, used by Alembic.
revision = '32447299a7db'
down_revision = 'a1485d740d43'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('shape', sa.String(), nullable=False),
    sa.Column('image', sa.Integer(), nullable=False),
    sa.Column('context_group', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.DateTime(), nullable=True),
    sa.Column('restored_by', sa.Integer(), nullable=True),
    sa.Column('restored', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['usergroup.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['usergroup.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['usergroup.id'], ),
    sa.ForeignKeyConstraint(['restored_by'], ['usergroup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('badgegiven',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badge.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['usergroup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('badgegiven')
    op.drop_table('badge')
    # ### end Alembic commands ###
