"""Modify LLMRule to save a singular API key

Revision ID: 3d617047978f
Revises: 03399434d3b8
Create Date: 2026-05-10 17:02:03.650593

"""

# revision identifiers, used by Alembic.
revision = "3d617047978f"
down_revision = "03399434d3b8"

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_rule", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("public_key", sa.String(), nullable=False, server_default="")
        )
        batch_op.add_column(
            sa.Column("provider", sa.String(), nullable=False, server_default="")
        )
        batch_op.add_column(
            sa.Column("api_key", sa.String(), nullable=False, server_default="")
        )
        batch_op.add_column(
            sa.Column(
                "groups",
                postgresql.ARRAY(sa.Integer()),
                nullable=False,
                server_default="{}",
            )
        )
        batch_op.add_column(
            sa.Column(
                "paths",
                postgresql.ARRAY(sa.String()),
                nullable=False,
                server_default="{}",
            )
        )
        batch_op.drop_column("apikey")
        batch_op.drop_column("chosen_key")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_rule", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "chosen_key",
                sa.VARCHAR(),
                autoincrement=False,
                nullable=False,
                server_default="",
            )
        )
        batch_op.add_column(
            sa.Column(
                "apikey",
                postgresql.ARRAY(sa.VARCHAR()),
                autoincrement=False,
                nullable=False,
                server_default="{}",
            )
        )
        batch_op.drop_column("paths")
        batch_op.drop_column("groups")
        batch_op.drop_column("api_key")
        batch_op.drop_column("provider")
        batch_op.drop_column("public_key")

    # ### end Alembic commands ###
