"""Add tables llm_rule, usage and policy

Revision ID: 3f418785dafb
Revises: e03fd2104ce9
Create Date: 2026-06-02 13:43:52.597851

"""

# revision identifiers, used by Alembic.
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa
from alembic import op

revision = "3f418785dafb"
down_revision = "e03fd2104ce9"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_rule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("owner", sa.Integer(), nullable=False),
        sa.Column("public_key", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("api_key", sa.String(), nullable=False),
        sa.Column("groups", postgresql.ARRAY(sa.Integer()), nullable=False),
        sa.Column("paths", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("use_streaming", sa.Boolean(), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=True),
        sa.Column("include_citations", sa.Boolean(), nullable=False),
        sa.Column("similarity_threshold", sa.Float(), nullable=True),
        sa.Column("top_k_chunks", sa.Integer(), nullable=False),
        sa.Column("current_mode", sa.String(), nullable=False),
        sa.Column("total_tokens_spent", sa.Integer(), nullable=False),
        sa.Column(
            "indexed_document_ids", postgresql.ARRAY(sa.Integer()), nullable=False
        ),
        sa.Column("system_prompt_path", sa.String(), nullable=False),
        sa.Column("agent", sa.String(), nullable=False),
        sa.Column("conv_time_window", sa.Integer(), nullable=False),
        sa.Column("conv_messages_max", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner"],
            ["useraccount.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "policy",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("for_user", sa.Integer(), nullable=True),
        sa.Column("llm_rule_id", sa.Integer(), nullable=False),
        sa.Column("token_time_window_type", sa.String(), nullable=True),
        sa.Column("token_time_window_num", sa.Integer(), nullable=True),
        sa.Column("time_window_tokens", sa.Integer(), nullable=True),
        sa.Column("max_tokens_per_user", sa.Integer(), nullable=True),
        sa.Column("token_pool", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["for_user"],
            ["useraccount.id"],
        ),
        sa.ForeignKeyConstraint(["llm_rule_id"], ["llm_rule.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "usage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user", sa.Integer(), nullable=False),
        sa.Column("llm_rule_id", sa.Integer(), nullable=False),
        sa.Column("used_tokens", sa.Integer(), nullable=False),
        sa.Column("token_usage_history", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["llm_rule_id"], ["llm_rule.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user"],
            ["useraccount.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("usage")
    op.drop_table("policy")
    op.drop_table("llm_rule")
    # ### end Alembic commands ###
