"""Add event.origin_doc_id

Revision ID: 3fec5685a240
Revises: e0ff4a70b73d
Create Date: 2022-12-13 17:31:13.454498

"""

# revision identifiers, used by Alembic.
revision = "3fec5685a240"
down_revision = "e0ff4a70b73d"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("event", sa.Column("origin_doc_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "event_origin_doc_id_fkey", "event", "block", ["origin_doc_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("event_origin_doc_id_fkey", "event", type_="foreignkey")
    op.drop_column("event", "origin_doc_id")
    # ### end Alembic commands ###
