"""Add NotificationType.AnswerAdded

Revision ID: 53c668fb0da1
Revises: e9a1132eec3c
Create Date: 2022-02-22 16:17:56.753911

"""

# revision identifiers, used by Alembic.
revision = "53c668fb0da1"
down_revision = "e9a1132eec3c"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pendingnotification", sa.Column("answer_number", sa.Integer(), nullable=True)
    )

    with op.get_context().autocommit_block():
        op.execute(
            """ALTER TYPE notificationtype ADD VALUE IF NOT EXISTS 'AnswerAdded'"""
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pendingnotification", "answer_number")
    # Don't drop notificationtype.AnswerAdded, as it can be used in the database.
    # ### end Alembic commands ###
