"""Badge and BadgeGiven: Fix foreign key references

Revision ID: 586290909cc8
Revises: 2a281f62cbfe
Create Date: 2025-03-24 09:57:55.363384

"""

# revision identifiers, used by Alembic.
revision = '586290909cc8'
down_revision = '2a281f62cbfe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.drop_constraint('badge_restored_by_fkey', type_='foreignkey')
        batch_op.drop_constraint('badge_deleted_by_fkey', type_='foreignkey')
        batch_op.drop_constraint('badge_created_by_fkey', type_='foreignkey')
        batch_op.drop_constraint('badge_modified_by_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'usergroup', ['context_group'], ['name'])
        batch_op.create_foreign_key(None, 'useraccount', ['restored_by'], ['id'])
        batch_op.create_foreign_key(None, 'useraccount', ['modified_by'], ['id'])
        batch_op.create_foreign_key(None, 'useraccount', ['created_by'], ['id'])
        batch_op.create_foreign_key(None, 'useraccount', ['deleted_by'], ['id'])

    with op.batch_alter_table('badgegiven', schema=None) as batch_op:
        batch_op.drop_constraint('badgegiven_withdrawn_by_fkey', type_='foreignkey')
        batch_op.drop_constraint('badgegiven_undo_withdrawn_by_fkey', type_='foreignkey')
        batch_op.drop_constraint('badgegiven_given_by_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'useraccount', ['withdrawn_by'], ['id'])
        batch_op.create_foreign_key(None, 'useraccount', ['undo_withdrawn_by'], ['id'])
        batch_op.create_foreign_key(None, 'useraccount', ['given_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badgegiven', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('badgegiven_given_by_fkey', 'usergroup', ['given_by'], ['id'])
        batch_op.create_foreign_key('badgegiven_undo_withdrawn_by_fkey', 'usergroup', ['undo_withdrawn_by'], ['id'])
        batch_op.create_foreign_key('badgegiven_withdrawn_by_fkey', 'usergroup', ['withdrawn_by'], ['id'])

    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('badge_modified_by_fkey', 'usergroup', ['modified_by'], ['id'])
        batch_op.create_foreign_key('badge_created_by_fkey', 'usergroup', ['created_by'], ['id'])
        batch_op.create_foreign_key('badge_deleted_by_fkey', 'usergroup', ['deleted_by'], ['id'])
        batch_op.create_foreign_key('badge_restored_by_fkey', 'usergroup', ['restored_by'], ['id'])

    # ### end Alembic commands ###
