"""Delete conversation_id from the Usage table

Revision ID: 5ea4bfb4b74c
Revises: 9e429147887d
Create Date: 2026-05-15 12:09:24.665118

"""

# revision identifiers, used by Alembic.
revision = "5ea4bfb4b74c"
down_revision = "9e429147887d"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usage", schema=None) as batch_op:
        batch_op.drop_column("conversation_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usage", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "conversation_id", sa.INTEGER(), autoincrement=False, nullable=False
            )
        )

    # ### end Alembic commands ###
