"""Add table for ics export url hash part

Revision ID: 67b119a88620
Revises: 95e86dded40a
Create Date: 2022-04-20 12:09:49.337873

"""

# revision identifiers, used by Alembic.
revision = '67b119a88620'
down_revision = '95e86dded40a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exportedcalendar',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('calendar_hash', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['useraccount.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exportedcalendar')
    # ### end Alembic commands ###
