"""Adjust nullability constraints

Revision ID: 6d83c36a6658
Revises: 14a649d37bc3
Create Date: 2024-02-12 13:49:14.697641

"""


# revision identifiers, used by Alembic.
revision = "6d83c36a6658"
down_revision = "14a649d37bc3"

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.alter_column("location", existing_type=sa.TEXT(), nullable=False)
        batch_op.alter_column("max_size", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("message", existing_type=sa.TEXT(), nullable=False)
        batch_op.alter_column(
            "signup_before",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=False,
        )

    with op.batch_alter_table("messagelist", schema=None) as batch_op:
        batch_op.alter_column(
            "manage_doc_id", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column("name", existing_type=sa.TEXT(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messagelist", schema=None) as batch_op:
        batch_op.alter_column("name", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column(
            "manage_doc_id", existing_type=sa.INTEGER(), nullable=True
        )

    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.alter_column(
            "signup_before",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=True,
        )
        batch_op.alter_column("message", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column("max_size", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("location", existing_type=sa.TEXT(), nullable=True)

    # ### end Alembic commands ###
