"""Delete apikey_provider from the LLMRule table.

Revision ID: 7c186be71ec9
Revises: 2de839f71c3e
Create Date: 2026-04-26 09:33:18.029110

"""

# revision identifiers, used by Alembic.
revision = '7c186be71ec9'
down_revision = '2de839f71c3e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_rule', schema=None) as batch_op:
        batch_op.drop_column('apikey_provider')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apikey_provider', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
