"""Add OAuth2 models

Revision ID: 8770c4966dc5
Revises: a057ebaa15a2
Create Date: 2021-08-10 07:47:25.216943

"""

# revision identifiers, used by Alembic.
revision = '8770c4966dc5'
down_revision = 'a057ebaa15a2'

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth2_auth_code',
                    sa.Column('code', sa.String(length=120), nullable=False),
                    sa.Column('client_id', sa.String(length=48), nullable=True),
                    sa.Column('redirect_uri', sa.Text(), nullable=True),
                    sa.Column('response_type', sa.Text(), nullable=True),
                    sa.Column('scope', sa.Text(), nullable=True),
                    sa.Column('nonce', sa.Text(), nullable=True),
                    sa.Column('auth_time', sa.Integer(), nullable=False),
                    sa.Column('code_challenge', sa.Text(), nullable=True),
                    sa.Column('code_challenge_method', sa.String(length=48), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['useraccount.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('code')
                    )
    op.create_table('oauth2_token',
                    sa.Column('client_id', sa.String(length=48), nullable=True),
                    sa.Column('token_type', sa.String(length=40), nullable=True),
                    sa.Column('access_token', sa.String(length=255), nullable=False),
                    sa.Column('refresh_token', sa.String(length=255), nullable=True),
                    sa.Column('scope', sa.Text(), nullable=True),
                    sa.Column('issued_at', sa.Integer(), nullable=False),
                    sa.Column('access_token_revoked_at', sa.Integer(), nullable=False),
                    sa.Column('refresh_token_revoked_at', sa.Integer(), nullable=False),
                    sa.Column('expires_in', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['useraccount.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('access_token')
                    )
    op.create_index(op.f('ix_oauth2_token_refresh_token'), 'oauth2_token', ['refresh_token'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oauth2_token_refresh_token'), table_name='oauth2_token')
    op.drop_table('oauth2_token')
    op.drop_table('oauth2_auth_code')
    # ### end Alembic commands ###
