"""Badge table: edit columns deleted and restored from Bool to DateTime

Revision ID: 88a01e3bdab7
Revises: 26c1a3c1beeb
Create Date: 2025-03-05 12:11:42.384745

"""

# revision identifiers, used by Alembic.
revision = '88a01e3bdab7'
down_revision = '26c1a3c1beeb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.alter_column('deleted',
               existing_type=sa.BOOLEAN(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('restored',
               existing_type=sa.BOOLEAN(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.alter_column('restored',
               existing_type=sa.DateTime(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.alter_column('deleted',
               existing_type=sa.DateTime(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
