"""Add color column to annotation table.

Revision ID: 88c3e145844b Revises: f469aa644049 Create Date: 2017-01-03 08:49:41.244996

"""

# revision identifiers, used by Alembic.
revision = '88c3e145844b'
down_revision = 'f469aa644049'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation', sa.Column('color', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotation', 'color')
    ### end Alembic commands ###
