"""policy items are now nullable

Revision ID: 9249bc8e6120
Revises: 3d617047978f
Create Date: 2026-05-11 12:28:53.936932

"""

# revision identifiers, used by Alembic.
revision = '9249bc8e6120'
down_revision = '3d617047978f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policy', schema=None) as batch_op:
        batch_op.alter_column('token_time_window_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('token_time_window_num',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('time_window_tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('max_tokens_per_user',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('token_pool',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policy', schema=None) as batch_op:
        batch_op.alter_column('token_pool',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('max_tokens_per_user',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('time_window_tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('token_time_window_num',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('token_time_window_type',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
