"""Rename column association to extra_info

Revision ID: 98ba8761af06
Revises: 0755b11fe161
Create Date: 2023-11-16 11:49:45.937188

"""

# revision identifiers, used by Alembic.
revision = "98ba8761af06"
down_revision = "0755b11fe161"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("userlogincode", schema=None) as batch_op:
        batch_op.add_column(sa.Column("extra_info", sa.String(), nullable=False))
        batch_op.drop_column("association")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("userlogincode", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("association", sa.VARCHAR(), autoincrement=False, nullable=False)
        )
        batch_op.drop_column("extra_info")

    # ### end Alembic commands ###
