"""Add Event.important

Revision ID: 98c571553028
Revises: 1a8792054f77
Create Date: 2022-09-05 08:37:48.515064

"""

# revision identifiers, used by Alembic.
revision = "98c571553028"
down_revision = "1a8792054f77"

import sqlalchemy as sa
from alembic import op


# noinspection SqlResolve
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("event", sa.Column("important", sa.Boolean(), nullable=True))
    op.execute("UPDATE event SET important = False")
    op.alter_column("event", "important", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("event", "important")
    # ### end Alembic commands ###
