"""Add style column to annotation and velp tables

Revision ID: 98d090356548
Revises: 53c668fb0da1
Create Date: 2022-03-07 14:07:19.796536

"""

# revision identifiers, used by Alembic.
revision = "98d090356548"
down_revision = "53c668fb0da1"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("annotation", sa.Column("style", sa.Integer(), nullable=True))
    op.add_column("velp", sa.Column("style", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("velp", "style")
    op.drop_column("annotation", "style")
    # ### end Alembic commands ###
