"""Add tables for LLMRule, Policy and Usage in the ChatTIM plugin.

Revision ID: 9c9b96ae1505
Revises: e03fd2104ce9
Create Date: 2026-04-22 09:09:37.864438

"""

# revision identifiers, used by Alembic.
revision = '9c9b96ae1505'
down_revision = 'e03fd2104ce9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=False),
    sa.Column('apikey_provider', sa.String(), nullable=False),
    sa.Column('apikey', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('chosen_key', sa.String(), nullable=False),
    sa.Column('teachers', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('current_mode', sa.String(), nullable=False),
    sa.Column('total_tokens_spent', sa.Integer(), nullable=False),
    sa.Column('indexed_chunk_ids', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('agent', sa.String(), nullable=False),
    sa.Column('conv_time_window', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['useraccount.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('for_user', sa.Integer(), nullable=True),
    sa.Column('llm_rule_id', sa.Integer(), nullable=False),
    sa.Column('token_time_window_type', sa.String(), nullable=False),
    sa.Column('token_time_window_num', sa.Integer(), nullable=False),
    sa.Column('time_window_tokens', sa.Integer(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('policy_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['for_user'], ['useraccount.id'], ),
    sa.ForeignKeyConstraint(['llm_rule_id'], ['llm_rule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('llm_rule_id', sa.Integer(), nullable=False),
    sa.Column('used_tokens', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['llm_rule_id'], ['llm_rule.id'], ),
    sa.ForeignKeyConstraint(['user'], ['useraccount.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usage')
    op.drop_table('policy')
    op.drop_table('llm_rule')
    # ### end Alembic commands ###
