"""Add model options to LLMRule table

Revision ID: 9e429147887d
Revises: 9249bc8e6120
Create Date: 2026-05-13 14:23:47.035854

"""

# revision identifiers, used by Alembic.
revision = "9e429147887d"
down_revision = "9249bc8e6120"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_rule", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "use_streaming", sa.Boolean(), nullable=False, server_default=sa.false()
            )
        )
        batch_op.add_column(sa.Column("temperature", sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_rule", schema=None) as batch_op:
        batch_op.drop_column("temperature")
        batch_op.drop_column("use_streaming")

    # ### end Alembic commands ###
