"""Rename BadgeStorage to Badge and BadgesGiven to BadgeGiven

Revision ID: a01677947fcf
Revises: c7b18f399d9c
Create Date: 2025-02-18 16:26:57.599685

"""

# revision identifiers, used by Alembic.
revision = 'a01677947fcf'
down_revision = 'c7b18f399d9c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('shape', sa.String(), nullable=False),
    sa.Column('image', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('badgegiven',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badge.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['usergroup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('badgesgiven')
    op.drop_table('badgestorage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badgestorage',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('badgestorage_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('shape', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='badgestorage_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('badgesgiven',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('badge_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badgestorage.id'], name='badgesgiven_badge_id_fkey'),
    sa.ForeignKeyConstraint(['group_id'], ['usergroup.id'], name='badgesgiven_group_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='badgesgiven_pkey')
    )
    op.drop_table('badgegiven')
    op.drop_table('badge')
    # ### end Alembic commands ###
