"""Add userlogincode.valid

Revision ID: a1485d740d43
Revises: 417094192806
Create Date: 2024-11-27 11:28:54.875564

"""

# revision identifiers, used by Alembic.
revision = "a1485d740d43"
down_revision = "417094192806"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("userlogincode", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("valid", sa.Boolean(), nullable=False, server_default="true")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("userlogincode", schema=None) as batch_op:
        batch_op.drop_column("valid")

    # ### end Alembic commands ###
