"""Add extra enrollments

Revision ID: a52fd641921f
Revises: d37c210f7269
Create Date: 2022-08-19 07:28:22.780931

"""

# revision identifiers, used by Alembic.
revision = "a52fd641921f"
down_revision = "d37c210f7269"

import sqlalchemy as sa
from alembic import op


# noinspection SqlResolve
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("enrollment", sa.Column("extra", sa.Boolean(), nullable=True))
    op.add_column("eventgroup", sa.Column("extra", sa.Boolean(), nullable=True))
    op.execute("UPDATE eventgroup SET extra = FALSE")
    op.execute("UPDATE enrollment SET extra = FALSE")
    op.alter_column("eventgroup", "extra", nullable=False)
    op.alter_column("enrollment", "extra", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("eventgroup", "extra")
    op.drop_column("enrollment", "extra")
    # ### end Alembic commands ###
