"""Add message verification type

Revision ID: a6614a0e59d3
Revises: 98c571553028
Create Date: 2022-09-21 08:19:19.744090

"""

# revision identifiers, used by Alembic.
revision = "a6614a0e59d3"
down_revision = "98c571553028"

import sqlalchemy as sa
from alembic import op

verification_type_enum = sa.Enum(
    "NONE", "FORWARD", "MUNGE_FROM", name="messageverificationtype"
)


# noinspection SqlResolve
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    verification_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "messagelist",
        sa.Column(
            "message_verification",
            verification_type_enum,
            nullable=False,
            server_default="MUNGE_FROM",
        ),
    )
    op.execute("UPDATE messagelist SET message_verification = 'NONE'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messagelist", "message_verification")
    verification_type_enum.drop(op.get_bind())
    # ### end Alembic commands ###
