"""Add active to Badge and BadgeGiven tables

Revision ID: ac701c242157
Revises: 3188df30c0d1
Create Date: 2025-03-03 12:01:33.370992

"""

# revision identifiers, used by Alembic.
revision = 'ac701c242157'
down_revision = '3188df30c0d1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('badgegiven', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badgegiven', schema=None) as batch_op:
        batch_op.drop_column('active')

    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
