"""adding usage history to Usage-table

Revision ID: bbf1b06b05ee
Revises: 24f3ff2b4ef5
Create Date: 2026-05-26 18:48:50.868563

"""

# revision identifiers, used by Alembic.
revision = "bbf1b06b05ee"
down_revision = "165d17108346"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usage", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "token_usage_history",
                sa.JSON(),
                nullable=False,
                server_default=sa.text("'[]'::json"),
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usage", schema=None) as batch_op:
        batch_op.drop_column("token_usage_history")

    # ### end Alembic commands ###
