"""Add table for steps phase

Revision ID: c18fb65697ee
Revises: 417094192806
Create Date: 2024-11-14 09:12:12.236411

"""

# revision identifiers, used by Alembic.
revision = "c18fb65697ee"
down_revision = "417094192806"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stepsphase",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("user_working_group", sa.Integer(), nullable=False),
        sa.Column("user_group", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("current_phase", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_group"],
            ["usergroup.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stepsphase")
    # ### end Alembic commands ###
