"""Allow nullable peer_review task_id

Revision ID: c4b0954330a3
Revises: ec2c8fa8dea3
Create Date: 2022-04-09 19:46:49.087267

"""

# revision identifiers, used by Alembic.
revision = 'c4b0954330a3'
down_revision = 'ec2c8fa8dea3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('peer_review', 'task_name',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('peer_review', 'task_name',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
