"""Add badge_id and group_id to BadgesGiven

Revision ID: c7b18f399d9c
Revises: ced8a5630839
Create Date: 2025-02-18 14:02:09.551193

"""

# revision identifiers, used by Alembic.
revision = 'c7b18f399d9c'
down_revision = 'ced8a5630839'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badgesgiven', schema=None) as batch_op:
        batch_op.add_column(sa.Column('badge_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'badgestorage', ['badge_id'], ['id'])
        batch_op.create_foreign_key(None, 'usergroup', ['group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badgesgiven', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('group_id')
        batch_op.drop_column('badge_id')

    # ### end Alembic commands ###
