"""Add database tables for badges

Revision ID: ced45d32bd7c
Revises: e03fd2104ce9
Create Date: 2025-09-11 09:44:47.656074

"""

# revision identifiers, used by Alembic.
revision = 'ced45d32bd7c'
down_revision = 'e03fd2104ce9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badgetemplate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('color', sa.Text(), nullable=False),
    sa.Column('shape', sa.Text(), nullable=False),
    sa.Column('image', sa.Integer(), nullable=False),
    sa.Column('context_group', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['context_group'], ['usergroup.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['useraccount.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('badge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('given_by', sa.Integer(), nullable=False),
    sa.Column('given', sa.DateTime(timezone=True), nullable=False),
    sa.Column('withdrawn', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badgetemplate.id'], ),
    sa.ForeignKeyConstraint(['given_by'], ['useraccount.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['usergroup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('badge')
    op.drop_table('badgetemplate')
    # ### end Alembic commands ###
