"""Add BadgeStorage and BadgesGiven

Revision ID: ced8a5630839
Revises: a1485d740d43
Create Date: 2025-02-18 12:50:08.384978

"""

# revision identifiers, used by Alembic.
revision = 'ced8a5630839'
down_revision = 'a1485d740d43'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badgesgiven',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('badgestorage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('shape', sa.String(), nullable=False),
    sa.Column('image', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('badgestorage')
    op.drop_table('badgesgiven')
    # ### end Alembic commands ###
