"""Add table for tracking task accesses

Revision ID: cfb47bb4ea55
Revises: 4b82ca7db0ed
Create Date: 2022-01-12 12:55:31.688469

"""

# revision identifiers, used by Alembic.
revision = "cfb47bb4ea55"
down_revision = "4b82ca7db0ed"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "taskblock",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["block.id"],
        ),
        sa.PrimaryKeyConstraint("id", "task_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("taskblock")
    # ### end Alembic commands ###
