"""Add many-to-many tags mapping for Event

Revision ID: d37c210f7269
Revises: 09bd8c793733
Create Date: 2022-08-16 08:36:23.989851

"""

# revision identifiers, used by Alembic.
revision = "d37c210f7269"
down_revision = "09bd8c793733"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "eventtag",
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("tag", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("tag_id"),
    )
    op.create_table(
        "eventtagattachment",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["event.event_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["eventtag.tag_id"],
        ),
        sa.PrimaryKeyConstraint("event_id", "tag_id"),
    )
    # It's okay to drop the old tag column, because it was never used.
    op.drop_column("event", "event_tag")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "event", sa.Column("event_tag", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_table("eventtagattachment")
    op.drop_table("eventtag")
    # ### end Alembic commands ###
