"""add user.tos_accepted_at

Revision ID: e03fd2104ce9
Revises: eccae2b73601
Create Date: 2025-07-14 05:59:49.234264

"""

# revision identifiers, used by Alembic.
revision = "e03fd2104ce9"
down_revision = "eccae2b73601"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("useraccount", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tos_accepted_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("useraccount", schema=None) as batch_op:
        batch_op.drop_column("tos_accepted_at")

    # ### end Alembic commands ###
