"""Add created column to internal messages

Revision ID: e0ff4a70b73d
Revises: be3366b49cb9
Create Date: 2022-12-13 14:13:56.906099

"""

# revision identifiers, used by Alembic.
revision = "e0ff4a70b73d"
down_revision = "be3366b49cb9"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "internalmessage",
        sa.Column("created", sa.DateTime(timezone=True), nullable=True),
    )
    op.execute("UPDATE internalmessage SET created = NOW()")
    op.alter_column("internalmessage", "created", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("internalmessage", "created")
    # ### end Alembic commands ###
