"""Add origin document and plugin type metadata to answers

Revision ID: e135a4bf42c8
Revises: 132d3c908b54
Create Date: 2021-08-11 09:06:50.189265

"""

# revision identifiers, used by Alembic.
revision = 'e135a4bf42c8'
down_revision = '132d3c908b54'

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('origin_doc_id', sa.Integer(), nullable=True))
    op.add_column('answer', sa.Column('plugin_type', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'answer', 'block', ['origin_doc_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.drop_column('answer', 'plugin_type')
    op.drop_column('answer', 'origin_doc_id')
    # ### end Alembic commands ###
