"""Add blockaccess.restricted

Revision ID: ea84897db6c8
Revises: e42c2fe768d2
Create Date: 2024-04-07 07:54:12.194448

"""

# revision identifiers, used by Alembic.
revision = "ea84897db6c8"
down_revision = "e42c2fe768d2"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blockaccess", schema=None) as batch_op:
        batch_op.add_column(sa.Column("restricted", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blockaccess", schema=None) as batch_op:
        batch_op.drop_column("restricted")

    # ### end Alembic commands ###
