"""Add UserGroupMember.membership_added

Revision ID: ec2c8fa8dea3
Revises: 98d090356548
Create Date: 2022-04-06 07:21:40.828026

"""

# revision identifiers, used by Alembic.
revision = "ec2c8fa8dea3"
down_revision = "98d090356548"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "usergroupmember",
        sa.Column(
            "membership_added",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usergroupmember", "membership_added")
    # ### end Alembic commands ###
