"""Add similarity_threshold and include_citations to LLMRule

Revision ID: fb976f3d5de8
Revises: 5ea4bfb4b74c
Create Date: 2026-05-19 21:37:12.000806

"""

# revision identifiers, used by Alembic.
revision = "fb976f3d5de8"
down_revision = "5ea4bfb4b74c"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_rule", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "include_citations",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
        batch_op.add_column(
            sa.Column(
                "similarity_threshold",
                sa.Float(),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_rule", schema=None) as batch_op:
        batch_op.drop_column("similarity_threshold")
        batch_op.drop_column("include_citations")

    # ### end Alembic commands ###
