#!/usr/bin/env bash

set -euo pipefail

DIR="$(git rev-parse --show-toplevel)"

. ${DIR}/variables.sh

PID=$(docker ps -q | xargs docker inspect --format '{{.State.Pid}}, {{.Name}}' | grep "${COMPOSE_PROJECT_NAME}_$1_1" | cut -f 1 -d ",")
TIMESTAMP=$(date +"%s")
FLAMEGRAPH_FILE="pyspy_$1_${TIMESTAMP}.svg"
sudo py-spy record -p "${PID}" -o "${DIR}/timApp/static/profiling/${FLAMEGRAPH_FILE}" --subprocesses
echo "Open flamegraph: ${TIM_HOST}/static/profiling/${FLAMEGRAPH_FILE}"
