version: "3.7"
x-common-agent:
 &common-agent
 tmpfs:
  - /run/sshd
  - /home/agent/.pycharm_helpers
  - /root/.pycharm_helpers
x-common-root:
 &common-root
 tmpfs:
  - /run/sshd
  - /root/.pycharm_helpers
services:
 tim:
  << : *common-root
  command: /usr/sbin/sshd -D
  ports:
   - "49999:22"
  depends_on:
   - postgresql-test
 postgresql:
  ports:
   - "5432:5432"
 postgresql-test:
  image: postgres:11
  ports:
   - "5433:5432"
  tmpfs:
   - /var/lib/postgresql/data
  restart: unless-stopped
  environment:
   POSTGRES_PASSWORD: postgresql
 imagex:
  << : *common-root
  image: timimages/cs3sudo:focal
  command: ${IMAGEX_DEV_COMMAND:-/usr/sbin/sshd -D}
  ports:
   - "49995:22"
 pali:
  << : *common-root
  command: ${PALI_DEV_COMMAND:-/usr/sbin/sshd -D}
  ports:
   - "49997:22"
 fields:
  << : *common-root
  command: ${TEXTFIELD_DEV_COMMAND:-/usr/sbin/sshd -D}
  ports:
   - "49990:22"
 jsrunner:
  << : *common-root
  command: ${JSRUNNER_DEV_COMMAND:-/usr/sbin/sshd -D}
  ports:
   - "49991:22"
 drag:
  << : *common-root
  command: ${DRAG_DEV_COMMAND:-/usr/sbin/sshd -D}
  ports:
   - "49980:22"
 feedback:
  << : *common-root
  command: ${FEEDBACK_DEV_COMMAND:-/usr/sbin/sshd -D}
  ports:
   - "49978:22"
 csplugin:
  << : *common-agent
  command: ${CSPLUGIN_DEV_COMMAND:-/usr/sbin/sshd -D}
  ports:
   - "49998:22"
 stack-api-server:
  << : *common-root
  image: timimages/stack-api:latest-dev
  restart: unless-stopped
  ports:
   - "49992:22"
 showfile:
  << : *common-agent
  image: timimages/cs3sudo:focal
  build:
   context: ./timApp/modules/cs
   target: sudo
  command: ${SVNPLUGIN_DEV_COMMAND:-/usr/sbin/sshd -D}
  ports:
   - "49996:22"
