#!/usr/bin/env bash

if [ ! -d "timApp/modules/cs/jsav" ]; then
  echo "ERROR: JSAV submodule is missing! Did you run \`git submodule update --init\` before running this?"
  exit 1
fi

set -e

# When building JSAV, don't use simply "npm install" because it also installs testing-related stuff such as PhantomJS.
# Just install the bare minimum grunt packages required for building it.
./run_command_workdir.sh timApp /bin/bash -c "\
npm install --unsafe-perm && \
(cd modules/cs/jsav && npm i --no-save grunt grunt-contrib-concat grunt-contrib-uglify grunt-exec load-grunt-tasks && echo NOTE: You can ignore all Local Npm module warnings. && npx grunt) && \
(cd modules/jsrunner/server && npm install --unsafe-perm)
"
