#!/usr/bin/env bash

if [ ! -d "timApp/modules/cs/jsav" ]; then
  echo "ERROR: JSAV submodule is missing! Did you run \`git submodule update --init\` before running this?"
  exit 1
fi

set -e

(cd timApp &&
  npm install &&
  npm run lint &&
  (cd modules/cs/jsav && npm i --no-save grunt grunt-contrib-concat grunt-contrib-uglify grunt-exec load-grunt-tasks && echo NOTE: You can ignore all Local Npm module warnings. && npx grunt))
# jsrunner cannot be installed in Windows because it needs to build native libraries.
# && (cd modules/jsrunner/server && npm install)

./run_command_workdir.sh timApp/modules/jsrunner/server bash -c "npm i --unsafe-perm --no-bin-links"
