#!/usr/bin/env bash

set -e

(cd timApp &&
  npm install &&
  npm run lint)
# jsrunner cannot be installed in Windows because it needs to build native libraries.
# && (cd modules/jsrunner/server && npm install)

./run_command_workdir.sh --dc-no-deps timApp/modules/jsrunner/server bash -c "npm i --unsafe-perm"
