[files]
extend-exclude = [
    "typos.toml",
    "*.c",
    "*.cc",
    "*.h",
    "*.cpp",
    "*.xlf",
    "*.patch",
    "*.min.js",
    "*-min.js",
    "timApp/templates/base.jinja2",
    "timApp/static/scripts/vendor/",
    "timApp/static/ohj1/",
    "timApp/modules/cs/static/ohj2/",
    "timApp/modules/cs/static/WeScheme/",
    "timApp/modules/cs/tauno/",
    "test_signup.py",
    "test_csplugin_replace_code.py",
    "full.render.js",
    "lite.render.js",
    "embedded_sagecell.js",
    "processing.js",
    "codeHighlight.scss",
    "timApp/migrations/versions/*.py",
]

[default.extend-identifiers]
# False positives/otherwise not worth fixing:
ba = "ba"
datas = "datas"
global_datas = "global_datas"
SMTPHeloError = "SMTPHeloError"
ba_group = "ba_group"
ue = "ue"
nd = "nd"
nd_path = "nd_path"
209fc28604ba = "209fc28604ba"
70a159e42ba6 = "70a159e42ba6"
82c3b050ba5d = "82c3b050ba5d"
209fc28604ba_ = "209fc28604ba_"
70a159e42ba6_ = "70a159e42ba6_"
82c3b050ba5d_add_index_to_readparagraphs = "82c3b050ba5d_add_index_to_readparagraphs"
Anonymoys = "Anonymoys"
ba_change = "ba_change"
ba_confirm = "ba_confirm"
GHYGje2NiYlQM66xyggsnzQht1OHSgtv_9baHbFIklU = "GHYGje2NiYlQM66xyggsnzQht1OHSgtv_9baHbFIklU"
Otho = "Otho"
makro = "makro"
euclidianView = "euclidianView"
alue = "alue"
uudenMuuttujanAlue = "uudenMuuttujanAlue"
muuttujaButtonAlue = "muuttujaButtonAlue"
alle = "alle"
funktion = "funktion"
t_lnBA = "t_lnBA"
rekursion = "rekursion"
als = "als"
ist = "ist"
sade = "sade"
addToDatas = "addToDatas"
sectionning = "sectionning"
eJwVy0EOhCAMQNG7dG0yahGFy5BaS2ZigEnFlfHu4vL95F8Q_qKJsuQKvuopHVDmb1HwAB0wJQlRS2r8vD40hlp2yS2YwTGamceerWXkaR0nIiTroiFaNtsPy = "eJwVy0EOhCAMQNG7dG0yahGFy5BaS2ZigEnFlfHu4vL95F8Q_qKJsuQKvuopHVDmb1HwAB0wJQlRS2r8vD40hlp2yS2YwTGamceerWXkaR0nIiTroiFaNtsPy"
Versio = "Versio"
MATA280 = "MATA280"
selectin = "selectin"
braket = "braket"
ND = "ND"
T3Pbw_JAT4jzxiFC47fCT9kChSyZpNDFmosuCA8Y6WE = "T3Pbw_JAT4jzxiFC47fCT9kChSyZpNDFmosuCA8Y6WE"
T3Pbw_ = "T3Pbw_"
JAT4jzxiFC47fCT9kChSyZpNDFmosuCA8Y6WE = "JAT4jzxiFC47fCT9kChSyZpNDFmosuCA8Y6WE"

[default.extend-words]
# Custom corrections:
'garåh' = "graph"
agording = "according"
allreadu = "already"
charracter = "character"
depreceted = "deprecated"
dirrerences = "differences"
helpper = "helper"
indesies = "indices"
lanbda = "lambda"
opertation = "operation"
opertator = "operator"
pahse = "phase"
parenthes = "parentheses"
phese = "phase"
refecence = "reference"
refreneces = "references"
releted = "related"
requrie = "require"
rexexp = "regexp"
sthe = "the"
whinch = "which"
