//  !"#$%&'()*+,-./0123456789:;<=>?
// @ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_
// `abcdefghijklmnopqrstuvwxyz{|}~
const char draw_font[] =
  "@@@@@@@@@@@@@@@@@`PHDBA@?`@@?`@@@@PHBOxPDOx`HD@@`D@`D@`D?`@@?`@@"
  "@@@@@@C~@`H@@@@@DA@xJBalQDSF`hJB`hJBqdQD[B`hNA@P@@@@HDC?PB@@@@@@"
  "@@@@IDK?PbP@@@@@@@@@A@K?@`P@@@@@`hJBqgqD[B`hNA@P?`HB@`K~@`HB@`K~"
  "@@@PHG~@`G|`D@@@@@@dPo~A`_}BI@@@@@@HAOxA@_xDB@@@???@pLC|?LC@pLC@"
  "p|OCp|OCp|OCpwx|??|XFA`XFA`XFA`XPDA@PDA@PDA@PDA~@`HB@`HB@`HB@`I~"
  "_dA@PDA@PDA@PDA@_`HB@`HB@`HB@`HB@@@@@@@XF@@@@@@@@@@XF@C?@A`X@@@@"
  "Cp`HB@`HBLaHJA`H@@AldiJRdiIl@@@@NDQb@ciF`hJBQC`@@@@@@@Cx@@@@@@@@"
  "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
  "@@@@@@@@@@@@@@@@LC@pLC@pL@@@LC@@YfXbQ@@@@@@@@@@@@DQD?dQDQOyDQ@@@"
  "DCaTde@xEIJRUC`P|iJR}@`PHEzRdix@NDRBSCA`dHjJQCh@LC@PH@@@@@@@@@@@"
  "GBA@PHB@`HA@PB@\\\\@`DA@HB@`HDA@apDIITNA@xUIHP@@@@@@@PDAC~DA@P@@@@"
  "@@@@@@@@@@@pLA@`@@@@@@C~@@@@@@@@@@@@@@@@@@@@LC@@@`HDB@`PHBA@`H@@"
  "DBaD`hJB`hIDJA@@DCAPDA@PDA@PDGp@NDRB@`HDNDB@`Ox@NDRB@`PxA@JBQC`@"
  "A@pTIDRDaOxDA@P@?hB@`O`D@`JBQC`@NDRB`KcD`hJBQC`@?`HBA@PHBA@PHB@@"
  "NDRB`dPxQHJBQC`@NDRB`hIFN`JBQC`@@@@@NC`@@C`x@@@@@@@@NC`@@C`xBC@@"
  "@`PHDBA@HA@HA@H@@@@@@Ox@@Ox@@@@@PB@PB@PBA@`PHD@@ODJB@`PXL@@@LC@@"
  "NDRBciJRdhr@PCp@DBaD`hJB?hJB`hH@~HRB`hSxaHJBaO`@NDRB`HB@`HBBQC`@"
  "~HRB`hJB`hJBaO`@?hB@`HCx`HB@`Ox@?hB@`HCx`HB@`H@@NDRB`HBN`hJBQC`@"
  "`hJB`hK~`hJB`hH@NA@PDA@PDA@PDC`@G@`HB@`HB@bHbG@@`hRHdJC@hIBHaHH@"
  "`HB@`HB@`HB@`Ox@`l[FjjjRdhJB`hH@`lJbhiJRdhjJahH@NDRB`hJB`hJBQC`@"
  "~HRB`hSx`HB@`H@@NDRB`hJB`iJJQCh@~HRB`hSxhIBHaHH@NDRB`d@xAHJBQC`@"
  "?a@PDA@PDA@PDA@@`hJB`hJB`hJBQC`@`hJBQDQDJB`hDA@@`hJB`iJRjjkFqhH@"
  "`dQDJB`PJBaDQHH@`hIDQB`hDA@PDA@@?`HBA@`PHDB@`Ox@?hB@`HB@`HB@`HC~"
  "`HA@HB@PB@`D@`H@?`HB@`HB@`HB@`K~DBaD``@@@@@@@@@@@@@@@@@@@@@@@@C?"
  "HA@H@@@@@@@@@@@@@@@@^HPB^hZBagh@`HB@nLRB`hJBqK`@@@@@ODJ@`HB@Pcp@"
  "@`HBNdZB`hJBQch@@@@@ODJB?hB@Pcp@GBH`HOx`HB@`HB@@@@@@^hZB`hYz@`K|"
  "`HB@nLRB`hJB`hH@@C@@LA@PDA@PDC`@@@p@C@PDA@PDaHQx`HB@`hRH|IBHaHH@"
  "LA@PDA@PDA@PDC`@@@@@iMjRdiJRdiH@@@@@nLRB`hJB`hH@@@@@NDRB`hJBQC`@"
  "@@@@nLRB`hKDnHB@@@@@NdZB`hIFN`HB@@@@oLJ@`HB@`H@@@@@@ODJ@\\@pBaG`@"
  "@@@`?B@`HB@`Hap@@@@@`hJB`hJBagh@@@@@`hJBQDPhJA@@@@@@diJRdjjjqhH@"
  "@@@@`hIDJA@hQHH@@@@@`dHbE@pDBHap@@@@?`PHDBA@`Ox@DA@PDA@PDA@PDA@P"
  "Ca@PDAC`DA@PDA@NxA@PDA@NDA@PDAC`@@@@@@A`d`p@@@@@jeVjUZiUjeVjUZiU"
  "@@@@\\hrHbHbHbGX@NDRB`hSxaHJBqKb@@@A@XZJTFA`iQXXBGBI@^HRB`hJBQC`@"
  "@@@@ODI@ODB@Pcp@@@@@@CqB`Gr@Pcp@@@@@wFIBPdIBPdHB@@@@pdIDREA`PDC@"
  "@@@@LA@PDA@PD`p@@@@@`hRHdOBHaHH@NDRB@`HFBaHbPlX@@@@@qdIBPdIBYei@"
  "@@@@qDIBQDaPXD@@@@@@QHJBdiJRdfp@@@@HNDrJdiJbYC``@@@@cIJRdiJR_A@P"
  "@@@@_jPdIBPdiDP@@@@@ueQTUEQTNA@P@@@@NDRB`hKDnHB@@@@@GsaD`hJBQC`@"
  "@@@@_i@PDA@PBPX@@@@xQDQD_DQDQC`@@@@Drd]BPdIBIA`@@@@@qDIBPdIDRC@@"
  "_bA@PCq@`D@|@`HL_`XXHDB@`D@|@`HLDA@pJBaHQDRB`ox@?dI@PDA@PDA@PN@@"
  "DA@pJBaHQDRB`l\\@NDRB`hJB`hIDJNx@_A@xUIJRdiITNAA|?dQDQDQDQDQDQNx@"
  "deQTUEQTUC`PDGp@?hI@HA@HDBA@`ox@NDRB`jjzjhJBQC`@?hH@@DQ|Q@@@aOx@"
  "YhfIbVX@h}RRdYX@@@@NClC_p@xN@@@@kjFgjT\\@KC@`HB@@IDJA`XFA`XFA`THd"
  "`XFA`XFA`XFA`XFA@@B@`HBVfYFQdP@@`HzQdXx@GBP\\AA`@XhAbDfH@VFQDQDP@"
  "YhfIbVX@ND@xAC`@cnFGbV\\@VFQDQDP@YhfIbVX@DCpPD@p@XhAbDfH@A@RfuYVU"
  "YhfIbVX@AFRFYQUecnFGbV\\@A@RfuYVU@@@G\\XGraGPG@@@@yxFA`XFA`XFA`XGg"
  "`XFA`XFA`XFA`XGgyxFA`XFA`XFA`XFA@PDGJReghJAnBPdI@@dIJR]`kjeiC``H"
  "DAIpdiIr@DQDJB`PtJbhjJ`A@T^ijZeG`HzQdXx@\\iUqDf\\@@@C~@@C~@@C~@@@@"
  "@@@@IAK?DbP@@@@@LDbHTCEJaHiq@@C~QDQDQDQDQDQDQDP@";
unsigned draw_font_size = 191;
const unsigned draw_font_width = 8, draw_font_height = 12;
