import * as angular from "angular";
import * as ad from "bootstrap";
import * as a from "tim/controllers/answerToQuestionController";
import * as b from "tim/controllers/breadcrumbs";
import * as c from "tim/controllers/createLectureCtrl";
import * as d from "tim/controllers/indexCtrl";
import * as e from "tim/controllers/lectureController";
import * as f from "tim/controllers/lectureInfoController";
import * as g from "tim/controllers/questionController";
import * as h from "tim/controllers/questionPreviewController";
import * as i from "tim/controllers/reviewController";
import * as j from "tim/controllers/showStatisticsToQuestionController";
import * as k from "tim/controllers/sidebarMenuCtrl";
import * as l from "tim/controllers/smallMenuCtrl";
import * as m from "tim/controllers/startController";
import * as n from "tim/controllers/userlistController";
import * as o from "tim/controllers/view/viewctrl";
import * as p from "tim/directives/annotation";
import * as q from "tim/directives/answerbrowser3";
import * as r from "tim/directives/bookmarks";
import * as s from "tim/directives/bootstrapPanel";
import * as t from "tim/directives/createItem";
import * as u from "tim/directives/loginMenu";
import * as v from "tim/directives/pareditor";
import * as w from "tim/directives/popUpDialog";
import * as x from "tim/directives/rightsEditor";
import * as y from "tim/directives/velpSelection";
import * as z from "tim/loadMap";
import * as ab from "tim/manageView/manageCtrl";
import * as ac from "tim/settingsView/settingsCtrl";
import {markAsUsed} from "tim/utils";
import $ = require("jquery");
import {ParCompiler} from "./services/parCompiler";

markAsUsed(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, ab, ac, ad);

$(document).ready(() => {
    angular.bootstrap(document, ["timApp"], {strictDi: false});
    ParCompiler.processAllMathDelayed($("body"), 1500);
});
