import sqlite3
create_script=open("../schematimber.sql",'r').read()
drop_script=open("../dropTimber.sql",'r').read()
connection = sqlite3.connect('tim.db')
cursor = connection.cursor()
cursor.executescript(drop_script)
connection.commit()
print("Timber stuff is now gone.")
cursor.executescript(create_script)
connection.commit()
print("Timber stuff has been created.")
cursor.close()
connection.close()