DATABASE           = './tim_files/tim.db'
DEBUG              = False
FILES_PATH         = 'tim_files'
LOG_PATH           = "../tim_logs/timLog.log"
MAX_CONTENT_LENGTH = 16 * 1024 * 1025
PASSWORD           = '4t95MHJj9h89y'
SECRET_KEY         = '85db8764yhfZz7-U.-y968buyn89b54y8y45tg'
UPLOAD_FOLDER      = "./media/images/"
USERNAME           = 'admin'
