CREATE TABLE Block (
id INTEGER NOT NULL,
latest_revision_id INTEGER NULL,
type_id INTEGER NOT NULL,

CONSTRAINT Block_PK 
	PRIMARY KEY (id)
)
;


CREATE TABLE UserGroup (
id INTEGER NOT NULL,

CONSTRAINT UserGroup_PK 
	PRIMARY KEY (id)
)
;


CREATE TABLE User (
id INTEGER NOT NULL,
name VARCHAR(100) NOT NULL,

CONSTRAINT User_PK 
	PRIMARY KEY (id)
)
;


CREATE TABLE Document (
id INTEGER NOT NULL,
name VARCHAR(100) NOT NULL,
UserGroup_id INTEGER NOT NULL,

CONSTRAINT Document_PK 
	PRIMARY KEY (id),
CONSTRAINT Document_id 
	FOREIGN KEY (UserGroup_id)
	REFERENCES UserGroup (id)
		ON DELETE NO ACTION
		ON UPDATE CASCADE
)
;


CREATE TABLE DocumentBlock (
Document_id INTEGER NOT NULL,
Block_id INTEGER NOT NULL,

CONSTRAINT DocumentBlocks_PK
	PRIMARY KEY (Document_id,Block_id),
CONSTRAINT DocumentBlocks_id 
	FOREIGN KEY (Document_id)
	REFERENCES Document (id)
		ON DELETE NO ACTION
		ON UPDATE CASCADE,
CONSTRAINT DocumentBlocks_id 
	FOREIGN KEY (Block_id)
	REFERENCES Block (id)
		ON DELETE NO ACTION
		ON UPDATE CASCADE
)
;


CREATE TABLE ReadRevision (
revision_id INTEGER NOT NULL,
Block_id INTEGER NOT NULL,
User_id INTEGER NOT NULL,

CONSTRAINT ReadRevision_PK
	PRIMARY KEY (Block_id,User_id),
CONSTRAINT ReadRevision_id 
	FOREIGN KEY (Block_id)
	REFERENCES Block (id)
		ON DELETE NO ACTION
		ON UPDATE CASCADE,
CONSTRAINT ReadRevision_id 
	FOREIGN KEY (User_id)
	REFERENCES User (id)
		ON DELETE NO ACTION
		ON UPDATE CASCADE
)
;


CREATE TABLE UserGroupMember (
UserGroup_id INTEGER NOT NULL,
User_id INTEGER NOT NULL,

CONSTRAINT UserGroupMembers_PK
	PRIMARY KEY (UserGroup_id,User_id),
CONSTRAINT UserGroupMembers_id 
	FOREIGN KEY (UserGroup_id)
	REFERENCES UserGroup (id)
		ON DELETE NO ACTION
		ON UPDATE CASCADE,
CONSTRAINT UserGroupMembers_id 
	FOREIGN KEY (User_id)
	REFERENCES User (id)
		ON DELETE NO ACTION
		ON UPDATE CASCADE
)
;


CREATE TABLE BlockAccess (
visible_from TIMESTAMP NOT NULL,
visible_to TIMESTAMP NULL,
Block_id INTEGER NOT NULL,
UserGroup_id INTEGER NOT NULL,

CONSTRAINT BlockAccess_PK
	PRIMARY KEY (Block_id,UserGroup_id),
CONSTRAINT BlockAccess_id 
	FOREIGN KEY (Block_id)
	REFERENCES Block (id)
		ON DELETE NO ACTION
		ON UPDATE CASCADE,
CONSTRAINT BlockAccess_id 
	FOREIGN KEY (UserGroup_id)
	REFERENCES UserGroup (id)
		ON DELETE NO ACTION
		ON UPDATE CASCADE
)
;


CREATE TABLE DocumentAccess (
visible_from TIMESTAMP NOT NULL,
visible_to TIMESTAMP NULL,
Document_id INTEGER NOT NULL,
UserGroup_id INTEGER NOT NULL,

CONSTRAINT DocumentAccess_PK
	PRIMARY KEY (Document_id,UserGroup_id),
CONSTRAINT DocumentAccess_id 
	FOREIGN KEY (Document_id)
	REFERENCES Document (id)
		ON DELETE NO ACTION
		ON UPDATE CASCADE,
CONSTRAINT DocumentAccess_id 
	FOREIGN KEY (UserGroup_id)
	REFERENCES UserGroup (id)
		ON DELETE NO ACTION
		ON UPDATE CASCADE
)
;
