name: Check formatting

on: [push, pull_request]

jobs:
  skip_check:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
        - id: skip_check
          uses: fkirc/skip-duplicate-actions@v5
          with:
              concurrent_skipping: 'same_content_newer'
              skip_after_successful_duplicate: 'true'

  ts_format:
    name: Check TypeScript formatting
    runs-on: ubuntu-latest

    needs: skip_check
    if: needs.skip_check.outputs.should_skip != 'true'

    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: |
          cd timApp
          rm package-lock.json
          npm install --unsafe-perm --legacy-peer-deps
          npm install --no-package-lock --legacy-peer-deps --no-save prettier@2.7.1
      - name: Check formatting
        run: cd timApp && npm run checkformat

  py_format:
    name: Check Python formatting
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.11"

    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "${{ env.PYTHON_VERSION }}"
          cache: poetry
      - name: Install dependencies
        run: |
          poetry env use "${{ env.PYTHON_VERSION }}"
          poetry install --only=dev
      - name: Run format
        run: .venv/bin/black --check .