name: Generate code statistics

on: push

jobs:
  ts_bundle_stats:
    name: Bundle stats for TypeScript
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Cache Angular build assets
        uses: actions/cache@v3
        with:
          path: timApp/.angular/cache
          key: ${{ runner.os }}-angular-cache-stats-${{ hashFiles('**/*.ts') }}
          restore-keys: |
            ${{ runner.os }}-angular-cache-stats-
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: |
            timApp/node_modules
          key: ${{ runner.os }}-ts-stats-npm-${{ hashFiles('timApp/package-lock.json') }}
      - name: Install packages
        run: |
          npm i --global npm@6
          cd timApp
          npm install
          npm install -g webpack-bundle-analyzer
      - name: Generate bundle statistics
        run: cd timApp && npm run statshtml
      - name: Upload stats
        uses: actions/upload-artifact@v3.0.0
        with:
          name: Bundle Report
          path: timApp/report.html